Resolves #26 Integrate eslint and prettier
ascentcore/outpost pull request #30
Opened 2022-07-20 09:13 UTC by anduxp

## Note: 
The rules are exceedingly strict and cumbersome.

_Closes #26_

2022-07-20 11:28 UTC, adamcorina commented on frontend/.eslintrc.json
> +  "extends": ["eslint:recommended", "plugin:react/recommended", "plugin:prettier/recommended"],
extends is still the old one; check Cezar's

2022-07-20 11:33 UTC, anduxp commented on frontend/.eslintrc.json
> +  "extends": ["eslint:recommended", "plugin:react/recommended", "plugin:prettier/recommended"],
'extends' was modified under package.json, as per Cezar's note, not under .eslintrc

2022-07-20 12:52 UTC, code31415926535 commented on frontend/package.json
> +  "lint": "eslint .",
`lint`, `lint:fix`, `format` should ho under `scripts` in order for them to be runnable.
Try running `npm run lint`.

2022-07-20 13:34 UTC, cezarderevlean requested changes

2022-07-20 13:34 UTC, cezarderevlean commented on frontend/tsconfig.json
> +  "exclude": ["node_modules", "build", "dist", "public", ".github"]
if we use `include`, we don't really need `exclude` too

[see why](https://www.typescriptlang.org/tsconfig#exclude)

2022-07-20 13:34 UTC, cezarderevlean commented on frontend/package.json
> +  "eslintConfig": {},
if we use `.eslintrc`, I'd remove the `eslintConfig` property from here altogether

but make sure that the changes you added to `.eslintrc` actually work as desired (both in terms of console errors/warnings and highlights/underlines from VSC) – one way to check this is to use double quotes for a string in a JS file.

2022-07-21 07:58 UTC, cezarderevlean requested changes

2022-07-21 07:58 UTC, cezarderevlean commented on frontend/.prettierrc
> +    "jsxBracketSameLine": false,
`jsxBracketSameLine` is [deprecated](https://prettier.io/docs/en/options.html#deprecated-jsx-brackets), please use `bracketSameLine`

and then run a format on `App.tsx` at least to see that it works and the bracket goes on the next line

2022-07-21 07:58 UTC, cezarderevlean commented on frontend/src/App.tsx
> +          rel="noopener noreferrer">
the bracket still is on the same line

2022-07-21 07:58 UTC, cezarderevlean commented on frontend/tsconfig.json
> +  // "exclude": ["node_modules", "build", "dist", "public", ".github"]
doesn't this produce an error? as far as I know .json doesn't allow comments

2022-07-21 08:33 UTC, cezarderevlean approved these changes

2022-07-21 08:52 UTC, merged